### ISSUE TITLE
请问，online表单设置按钮，绑定JAVA增强或SQL增强，无法多选，只能一次选一条

### ISSUE THREAD

**Issue by 793292556** [jeecgboot/jeecg-boot#2766]
##### 问题描述：
online表单设置按钮，绑定JAVA增强或SQL增强，无法多选，对次表单数据只能一次选一条，有办法解决吗？一次选择多条，将多条JSON对象的JSON传送给后台

##### 截图&代码：

![image](https://user-images.githubusercontent.com/66394184/124873222-c383a480-dff8-11eb-9e34-6b4e71c7ec1b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tb2888** [comment]
我也想这样问！支持你

**Comment by jeffZbj** [comment]
同问

**Comment by zhangdaiscott** [comment]
已完成，下个版本发布

**Comment by jeffZbj** [comment]
请问大佬，下个版本大概什么时候发布，是否可以在2.4.5上增量


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月3日(星期二) 下午3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 请问，online表单设置按钮，绑定JAVA增强或SQL增强，无法多选，只能一次选一条 (#2766)





 
已完成，下个版本发布
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
