### ISSUE TITLE
online表单开发date类型保存后列表显示是时间戳，没有格式化过

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#3051]
##### 版本号：
2.4.6

##### 问题描述：
online表单开发date类型保存后列表显示是时间戳，没有格式化过

##### 截图&代码：
![image](https://user-images.githubusercontent.com/90361617/134286691-dbdbbc5e-fb7f-4b92-9123-be3886a3c2c4.png)
![image](https://user-images.githubusercontent.com/90361617/134286712-abe95044-55e1-4cf4-90c5-7c7152a56f5f.png)
![image](https://user-images.githubusercontent.com/90361617/134286741-dafb2b17-afae-491d-a132-d6114de16e54.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 3509282792** [comment]
boss在吗，求回复，是问题还是本来就这样呀，需要我自己格式化吗

**Comment by qiaochengqiang** [comment]
同问

**Comment by 3509282792** [comment]
怎么木有答复类

**Comment by zhangdaiscott** [comment]
什么数据库？什么情况下，我们未重现

**Comment by zhangdaiscott** [comment]
已经修复，请更新代码

**Comment by qiaochengqiang** [comment]
非常感谢，已经正常了，但是更新完没看懂是如何修复呢？ 麻烦有时间给解释一下。

***@***.***
 
发件人： ***@***.***
发送时间： 2021-09-26 17:40
收件人： jeecgboot/jeecg-boot
抄送： qiaochengqiang; Comment
主题： Re: [jeecgboot/jeecg-boot] online表单开发date类型保存后列表显示是时间戳，没有格式化过 (#3051)
Closed #3051.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
