### ISSUE TITLE
Some cryptographic suggestions

### ISSUE THREAD

**Issue by Gax-c** [jeecgboot/jeecg-boot#6202]

**Comment by zhangdaiscott** [comment]
cr

**Comment by EightMonth** [comment]
What you said is very instructive, but unfortunately, the Jeecg open source team is not good at security engineering, so we can only provide basic security protection. Also, because Jeecg is an open source project, and when it comes to using security algorithms, we have achieved a small amount of changes to complete security algorithm changes, so we more advocate that you can modify the algorithm and choose a security algorithm that fits your field.
